Add nm2, μm2 (area) and nm (length) units
convert-units/convert-units pull request #225
Opened 2021-11-10 16:22 UTC by Aleaxandre

2021-11-11 17:05 UTC, Taar requested changes
The area units look good but I'm confused by the PR's title. `nm` is already a unit of `length`. So was the goal to add in additional unit tests for `nm`?

2021-11-11 17:05 UTC, Taar commented on src/definitions/__tests__/length.test.ts
> +});
This test case already exists
```suggestion
```

2021-11-11 17:05 UTC, Taar commented on src/definitions/__tests__/length.test.ts
> +});
This test case already exists
```suggestion
```

2021-11-11 17:31 UTC, Aleaxandre commented
Sorry, my mistake, I updated the pull request the way you suggested.
Thanks !

2021-11-11 18:31 UTC, Taar approved these changes

2021-11-11 18:32 UTC, merged

2021-11-29 16:01 UTC, cyrinebensalem commented
hello @Taar  can we have a release including this update? thank you

2022-01-07 16:13 UTC, Taar commented
> hello @Taar can we have a release including this update? thank you

https://www.npmjs.com/package/convert-units/v/3.0.0-beta.3