Setting a more precise conversion from metric to imperial
convert-units/convert-units pull request #321
Opened 2024-05-31 12:42 UTC by johannesschaefer

The current conversion is missing two digests at the end.  Here is an example how the calculation goes wrong:
Math.round(4677.6713*(1/0.453592)) -> 10313
but the right would be 
Math.round(4677.6713*(1/0.45359237)) -> 10312

2024-05-31 21:21 UTC, Taar requested changes
Thanks for the PR! I agree that the conversions between systems should follow any defined standard where possible. However, I cannot accept this PR in its current state because the changes fail a test. Once that test has been fixed and passes then I'd be happy to merge this PR if all tests continue to pass and there aren't any linter errors.

2024-05-31 21:22 UTC, Taar commented
One other thing, maybe it would be worth adding a test for the case you've mentioned to serve as proof that the changes do indeed function as expected. Let me know your thoughts!

2024-05-31 21:33 UTC, johannesschaefer commented
Thanks for your hint. I fixed the test case and added a new one.

2024-06-01 03:48 UTC, Taar approved these changes
Thanks for fixing that test case and adding a new one. Much appreciated!

2024-06-01 03:49 UTC, merged